# GitHub Sponsors & Funding

# GitHub Sponsors
# github: [your-github-username]

# Patreon
# patreon: winncore

# Open Collective
# open_collective: winncore

# Ko-fi
# ko_fi: winncore

# Buy Me a Coffee
# buy_me_a_coffee: winncore

# Custom funding links
custom: ['mailto:zw@winncore.com?subject=WinnCore%20Sponsorship']

# Note: Uncomment and update the above lines once funding accounts are set up
# For now, enterprise support available via email: zw@winncore.com
