blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/WinnCore/Quantum-Resistant-File-Monitoring/discussions
    about: Ask questions and discuss ideas with the community

  - name: 📖 Documentation
    url: https://github.com/WinnCore/Quantum-Resistant-File-Monitoring/tree/main/docs
    about: Check the documentation for guides and references

  - name: 🔒 Security Vulnerability
    url: https://github.com/WinnCore/Quantum-Resistant-File-Monitoring/security/policy
    about: Report security vulnerabilities privately (DO NOT open public issues)

  - name: 💼 Enterprise Support
    url: mailto:zw@winncore.com
    about: Contact for enterprise support and consulting
